INSERT INTO USER(EMAIL,PASSWORD) VALUES('user@test.com','$2a$10$M6iubM5bteo5fv0pn7IqBuTcYa59Vo.v8TQRJbnXMmtSn2TE7QpMe');
INSERT INTO USER(EMAIL,PASSWORD) VALUES('user2@test.com','$2a$10$M6iubM5bteo5fv0pn7IqBuTcYa59Vo.v8TQRJbnXMmtSn2TE7QpMe');
INSERT INTO FILM_CATEGORY(NAME,AVAILABLE_CONTENT,PRICE,CURRENCY) VALUES('Dutch Films',10,400,'EUR');
INSERT INTO FILM_CATEGORY(NAME,AVAILABLE_CONTENT,PRICE,CURRENCY) VALUES('Dutch Series',10,400,'EUR');
INSERT INTO FILM_CATEGORY(NAME,AVAILABLE_CONTENT,PRICE,CURRENCY) VALUES('International Films',10,500,'EUR');
